In [1]:
import numpy as np

BASICS

In [2]:
a=np.array([1,2,3],dtype="int16")
print(a)

[1 2 3]


In [3]:
b=np.array([[9.1,4,6.0,7],[3,4,2,1],[1,9,4,5]])
print(b)
c=np.array([[[1,2,3],[3,5,6],[4,7,8]]])
print(c)

[[9.1 4.  6.  7. ]
 [3.  4.  2.  1. ]
 [1.  9.  4.  5. ]]
[[[1 2 3]
  [3 5 6]
  [4 7 8]]]


In [4]:
# Get dimension
a.ndim

1

In [5]:
b.ndim

2

In [6]:
c.ndim


3

In [7]:
#get shape
a.shape


(3,)

In [8]:
b.shape

(3, 4)

In [9]:
c.shape

(1, 3, 3)

In [10]:
#get type
a.dtype

dtype('int16')

In [11]:
#get size
a.itemsize

2

In [12]:
b.itemsize

8

8 bytes

In [13]:
#get m*n
a.size

3

In [14]:
b.size

12

In [15]:
c.size

9

total size=m*n

In [16]:
#get total size
a.nbytes

6

In [17]:
b.nbytes

96

nbytes=size*itemsize

Accessing /changing specific elements, rows, columns, etc

In [18]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [19]:
a[1,5]

13

In [20]:
a[0,5]

6

In [21]:
#get a specific row

In [22]:
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [23]:
#get a pecific column
a[:,2]

array([ 3, 10])

getting a little more fancy [startindex:endindex:stepsize]

In [24]:
a[0,1:6:2]

array([2, 4, 6])

In [25]:
a[0,1:-1:2]

array([2, 4, 6])

In [26]:
a[1,5]=20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [27]:
a[:,2]=[1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [28]:
b=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [29]:
#get specific element(work outside in)
b[0,1,1]

4

In [30]:
b[1,0,1]

6

In [31]:
b[:,1,:]

array([[3, 4],
       [7, 8]])

In [32]:
b[:,0,:]

array([[1, 2],
       [5, 6]])

In [33]:
b[:,1,:]=[[9,9],[8,8]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


INITIALIZING DIFFERENT TYPES OF ARRAYS

zeros matrix

In [34]:
# 1s matrix
np.ones((4,5,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [35]:
#any other number
np.full((2,4),3)

array([[3, 3, 3, 3],
       [3, 3, 3, 3]])

In [36]:
#any other number (full_like)
np.full_like(a,5)

array([[5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5]])

In [37]:
# random decimal numbers
np.random.rand(4,2,3)

array([[[0.2988882 , 0.11067559, 0.29886567],
        [0.16360493, 0.34685478, 0.97759861]],

       [[0.18069227, 0.88901339, 0.63338239],
        [0.24716716, 0.64023556, 0.08271277]],

       [[0.7151811 , 0.65150027, 0.49719245],
        [0.22210449, 0.89002013, 0.65978475]],

       [[0.9645972 , 0.67183258, 0.96372808],
        [0.90055639, 0.28693563, 0.64274982]]])

In [38]:
np.random.random_sample(a.shape)

array([[0.65185177, 0.98530376, 0.5925843 , 0.33931545, 0.17092645,
        0.21807364, 0.92434155],
       [0.72292579, 0.44409632, 0.47390022, 0.83215499, 0.44961871,
        0.75175817, 0.85136277]])

In [39]:
# random integer values
np.random.randint(10,size=(4,3))

array([[3, 7, 7],
       [9, 6, 1],
       [4, 3, 6],
       [9, 6, 7]])

# identity matrix


In [40]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# repeat  an array

In [41]:
arr=np.array([1,2,3])
r1=np.repeat(arr,4)
print(r1)

[1 1 1 1 2 2 2 2 3 3 3 3]


# repeat for 2d we use axis=0

In [42]:
#2d
arr=np.array([[1,2,3]])
r1=np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [43]:
output=np.ones((5,5))
print(output)
z=np.zeros((3,3))
z[1,1]=9
print(z)
output[1:-1,1:-1]=z
#output[1:4,1:4]=z is same
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


# be care when copying arrays!!!

In [44]:
a=np.array([1,2,3])
b=a.copy()
b[0]=100
print(b)
print(a)

[100   2   3]
[1 2 3]


# Mathematics


In [45]:
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [46]:
a+2

array([3, 4, 5, 6])

In [47]:
a-2

array([-1,  0,  1,  2])

In [48]:
a*2

array([2, 4, 6, 8])

In [49]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [50]:
b=np.array([1,2,3,4])
a+b

array([2, 4, 6, 8])

In [51]:
a**2

array([ 1,  4,  9, 16])

In [52]:
#take the sin
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

# linear algebra

### matrix multiplication

In [53]:
a=np.ones((2,3))
print(a)
b=np.full((3,2),2)
print(b)
np.dot(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

## determinant

In [54]:
c=np.identity(3)
print(c)
np.linalg.det(c)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


1.0

## statistics

In [55]:
stats=np.array([[2,2,3],[4,5,6]])
print(stats)

[[2 2 3]
 [4 5 6]]


In [56]:
np.min(stats)

2

In [57]:
np.min(stats, axis=1)

array([2, 4])

In [58]:
np.min(stats,axis=0)

array([2, 2, 3])

In [59]:
np.max(stats)

6

In [60]:
np.max(stats,axis=0)

array([4, 5, 6])

In [61]:
np.sum(stats,axis=0)

array([6, 7, 9])

In [62]:
np.sum(stats,axis=1)

array([ 7, 15])

In [74]:
before=np.array([[1,2,3,4],[5,6,7,8]])
print(before.shape)
after=before.reshape((2,2,2))
print(after)

(2, 4)
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### vertical and horizontal stacking vectors

In [75]:
v1=np.array([1,2,3,4])
v2=np.array([5,6,7,8])
print(v1)
print(v2)

[1 2 3 4]
[5 6 7 8]


In [78]:
np.vstack([v1,v2,v1,v2,v1])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4]])

In [81]:
np.hstack((v1,v2))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [82]:
h1=np.ones([2,4])
h2=np.zeros([2,2])
np.hstack([h1,h2])

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

# miscellaneous
### load data from file
#### f=np.genfromtxt('name of the file',delimeter=',')
#### f.astype('int32')

f[f>50]